github:
  description: "Apache OFBiz is an open source product for the automation of enterprise processes. It includes framework components and business applications for ERP, CRM, E-Business/E-Commerce, Supply Chain Management and Manufacturing Resource Planning. OFBiz provides a foundation and starting point for reliable, secure and scalable enterprise solutions."
  homepage:  https://ofbiz.apache.org/
  labels:
    - ofbiz
    - plugins
    - xml
    - java
    - groovy
    - javascript
    - web-framework
    - database
    - network-server
    - https
    - content
    - geospatial
